apiVersion: apps/v1
kind: Deployment
metadata:
  name: volare-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volare-api-gateway
  template:
    metadata:
      labels:
        app: volare-api-gateway
    spec:
      containers:
        - name: volare-api-gateway
          image: suhailabdaz/volare-api-gateway:latest
          ports:
            - containerPort: 4000
          env:
          - name: API_GATEWAY_PORT
            valueFrom:
              secretKeyRef:
                name: volare-secrets
                key: API_GATEWAY_PORT
          - name: RABBITMQ_LINK
            valueFrom:
              secretKeyRef:
                name: volare-secrets
                key: RABBITMQ_LINK
          - name: BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: volare-secrets
                key: BUCKET_NAME
          - name: BUCKET_REGION
            valueFrom:
              secretKeyRef:
                name: volare-secrets
                key: BUCKET_REGION
          - name: ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: volare-secrets
                key: ACCESS_KEY
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: volare-secrets
                key: SECRET_KEY
          - name: STRIPE_WEBHOOK_SECRET
            valueFrom:
              secretKeyRef:
                name: volare-secrets
                key: STRIPE_WEBHOOK_SECRET
          - name: STRIPE_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: volare-secrets
                key: STRIPE_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: volare-api-gateway-service
spec:
  type: NodePort
  selector:
    app: volare-api-gateway
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
    nodePort: 32000