apiVersion: v1
kind: Service
metadata:
  name: volare-authority-service
spec:
  ports:
    - port: 4003
  selector:
    app: volare-authority-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volare-authority-service
spec:
  selector:
    matchLabels:
      app: volare-authority-service
  replicas: 1
  template:
    metadata:
      labels:
        app: volare-authority-service
    spec:
      containers:
        - name: volare-authority-service
          image: suhailabdaz/volare-authority-service:latest
          ports:
            - containerPort: 4003
          env:
            - name: AUTHORITY_PORT
              valueFrom:
                secretKeyRef:
                  name: volare-secrets
                  key: AUTHORITY_PORT
            - name: RABBITMQ_LINK
              valueFrom:
                secretKeyRef:
                  name: volare-secrets
                  key: RABBITMQ_LINK
            - name: AUTHORITY_MONGODB_NAME
              valueFrom:
                secretKeyRef:
                  name: volare-secrets
                  key: AUTHORITY_MONGODB_NAME
            - name: AUTHORITY_MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: volare-secrets
                  key: AUTHORITY_MONGO_URI
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: volare-secrets
                  key: ACCESS_TOKEN
            - name: REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: volare-secrets
                  key: REFRESH_TOKEN