apiVersion: v1
kind: Service
metadata:
  name: volare-auth-service
spec:
  ports:
    - port: 4005
  selector:
    app: volare-auth-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volare-auth-service
spec:
  selector:
    matchLabels:
      app: volare-auth-service
  replicas: 1
  template:
    metadata:
      labels:
        app: volare-auth-service
    spec:
      containers:
        - name: volare-auth-service
          image: suhailabdaz/volare-auth-service:latest
          ports:
            - containerPort: 4005
          env:
            - name: AUTH_PORT
              valueFrom:
                secretKeyRef:
                  name: volare-secrets
                  key: AUTH_PORT
            - name: RABBITMQ_LINK
              valueFrom:
                secretKeyRef:
                  name: volare-secrets
                  key: RABBITMQ_LINK
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: volare-secrets
                  key: ACCESS_TOKEN
            - name: REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: volare-secrets
                  key: REFRESH_TOKEN